### ISSUE TITLE
How do I install example-htslib?

### ISSUE THREAD

**Issue by endrebak** [jmarshall/example-htslib#1]
I am trying to understand how to install and use the C-api for htslib. 

To begin with, I'd like to play around with your example. How do I get it to install? 

```
biocore-home ~/c/example-htslib (master D=) make Makefile.in
make: Nothing to be done for 'Makefile.in'.
biocore-home ~/c/example-htslib (master D=) make
make: *** No targets specified and no makefile found.  Stop.
biocore-home ~/c/example-htslib (master D=) configure.ac
configure.ac: command not found
biocore-home ~/c/example-htslib (master D=) ./configure.ac
Failed to execute process './configure.ac'. Reason:
exec: Exec format error
The file './configure.ac' is marked as an executable but could not be run by the operating system.
biocore-home ~/c/example-htslib (master D=) bash install-sh
install-sh: no input file specified.
```

**Comment by jmarshall** [comment]
This is an example for people wanting to use HTSlib from their own autoconf-using projects. Such people already know how to use autoconf, which is the step you are missing. You should read the [autoconf manual](https://www.gnu.org/software/autoconf/manual/) and the [autotools mythbuster](https://autotools.io/) to learn this.

Briefly, the process is

```
autoconf
./configure [--with-htslib=…]    # see ./configure --help and samtools's INSTALL
make
```

Because this is an example and a git repository, you need to run `autoconf` to set up to build this project. If this were a proper project release tarball, this would already have been done and the resulting _configure_ script would already exist. But it's neither of those.

The remaining steps are the usual ones as listed in [[configure-based] Basic Installation](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Basic-Installation.html), but as this is a trivial example there is no `make install` target to run.

I was planning to write a README with this information, which it seems would be useful.

**Comment by endrebak** [comment]
Thank you for the prompt reply. I will read your suggestions :)
